force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Used for ID&amp;V Question Bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/QuestionText__c.field-meta.xml
<CustomField>
    <fullName>QuestionText__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QuestionController.cls
public with sharing class QuestionController {
    
    @AuraEnabled(cacheable=true)
    public static Question__c getRandomActiveQuestion() {
        List<Question__c> activeQuestions = [SELECT Id, QuestionText__c FROM Question__c WHERE Active__c = true];
        if (!activeQuestions.isEmpty()) {
            Integer randomIndex = Math.mod(Math.abs(Crypto.getRandomInteger()), activeQuestions.size());
            return activeQuestions.get(randomIndex);
        } else {
            return null;
        }
    }
    
}